version: '3.8'

services:
  nextcloud-db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - nextcloud_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
    networks:
      - office-network

  nextcloud-redis:
    image: redis:alpine
    restart: always
    networks:
      - office-network

  nextcloud-app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - REDIS_HOST=nextcloud-redis
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - office-network

  nextcloud-web:
    image: nginx:alpine
    restart: always
    volumes:
      - nextcloud_data:/var/www/html:ro
      - ./config/nextcloud-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextcloud-app
    ports:
      - "8081:80"
    networks:
      - office-network
      - infrastructure_default

  onlyoffice-app:
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=secret
    ports:
      - "8082:80"
    networks:
      - office-network
      - infrastructure_default

volumes:
  nextcloud_db:
  nextcloud_data:


networks:
  office-network:
    ipam:
      config:
        - subnet: 172.31.1.0/24
  infrastructure_default:
    external: true
